### ISSUE TITLE
Add dav1d codec

### ISSUE THREAD

**Issue by Aleksid1** [markus-perl/ffmpeg-build-script#105]
Please add dav1d codec. Because libaom is slow for AV1 decoding and SVT-AV1 is only for x86 computers (cannot be used on M1 Mac). dav1d is used by default since FFmpeg 4.3.

**Comment by rokibhasansagar** [comment]
`dav1d` codec needs `python`, `ninja-build` and `meson` to build on a system.

Tried a build in linux for dav1d decoder, but not tested yet.
And MacOS implementation is also to be fixed later on.

Then, I can be able to add the feature.

**Comment by Aleksid1** [comment]
Thanks! Good luck,

**Comment by rokibhasansagar** [comment]
Just need to test the build again.
Then I'll do a PR for inclusion.

**Comment by rokibhasansagar** [comment]
Waiting for #107 to pass checks

**Comment by Aleksid1** [comment]
AV1 decoding via dav1d works fine on M1 Mac now. Many thanks!
