### ISSUE TITLE
needs to download waf tool

### ISSUE THREAD

**Issue by speculatrix** [markus-perl/ffmpeg-build-script#116]
I had to manually download waf tool and make it executable.

not a biggie but I had to research where this thing came from

**Comment by rokibhasansagar** [comment]
For the lv2 plug-in compilation, `waf` executable file is already provided in their repository. And the build script uses the available executable file to compile lv2.
So, installing `waf` externally is not a dependency.

**Comment by AriESQ** [comment]
```
building lv2 - version 1.18.2
=======================
lv2-1.18.2.tar.bz2 has already downloaded.
Extracted lv2-1.18.2.tar.bz2
$ ./waf configure --prefix=/home/ad/ffmpeg-build-script/workspace --lv2-user
/usr/bin/env: 'python': No such file or directory

Failed to Execute ./waf configure --prefix=/home/ad/ffmpeg-build-script/workspace --lv2-user
```

I've encountered the same bug. I'm on a very minimal install of debian, which appears to have `python3` installed, but not an executable for `python`.

A solution was to symlink /usr/bin/python to point at /usr/bin/python3. `sudo ln -s /usr/bin/python3 /usr/bin/python`

If there is a more proper software development way to do this, I would like to know. I suppose I could see declaring this as an env variable at the start of the script running as an alternative.

**Comment by speculatrix** [comment]
there's sufficient information for anyone else who has this problem to fix it.
