### ISSUE TITLE
Not compiling pkg-config on ubuntu17.04

### ISSUE THREAD

**Issue by voxsoftware** [markus-perl/ffmpeg-build-script#13]
Ubuntu 17.04
64 bits 
8 GB RAM
Procesador intel core i5 4 CPUS

Output:
make  all-recursive
make[1]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1'
Making all in glib
make[2]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
make  all-recursive
make[3]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
Making all in .
make[4]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
make[4]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
Making all in m4macros
make[4]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/m4macros'
make  all-am
make[5]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/m4macros'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/m4macros'
make[4]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/m4macros'
Making all in glib
make[4]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
  GEN      glibconfig-stamp
config.status: executing glib/glibconfig.h commands
config.status: glib/glibconfig.h is unchanged
make  all-recursive
make[5]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
Making all in libcharset
make[6]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib/libcharset'
make  all-am
make[7]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib/libcharset'
make[7]: Nothing to be done for 'all-am'.
make[7]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib/libcharset'
make[6]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib/libcharset'
Making all in . 
make[6]: Entering directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
  CC       libglib_2_0_la-gdate.lo
  CC       libglib_2_0_la-ghostutils.lo
  CC       libglib_2_0_la-ghook.lo
  CC       libglib_2_0_la-ghmac.lo
gdate.c: In function ‘g_date_strftime’:
gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
       tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
       ^~~~~~
  CC       libglib_2_0_la-giochannel.lo
  CC       libglib_2_0_la-gkeyfile.lo
  CC       libglib_2_0_la-glib-init.lo
cc1: some warnings being treated as errors
Makefile:1387: recipe for target 'libglib_2_0_la-gdate.lo' failed
make[6]: *** [libglib_2_0_la-gdate.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
make[6]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
Makefile:1934: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
Makefile:953: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib/glib'
Makefile:1046: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
Makefile:770: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1/glib'
Makefile:707: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kodhe/james/projects/ffmpeg-build-script/packages/pkg-config-0.29.1'
Makefile:463: recipe for target 'all' failed
make: *** [all] Error 2

Failed to Execute make -j 4

**Comment by LauriTK** [comment]
Try this https://bugs.freedesktop.org/show_bug.cgi?id=95326
