### ISSUE TITLE
[all platforms] Zlib has incremented to version 1.2.13

### ISSUE THREAD

**Issue by scgreenhalgh** [markus-perl/ffmpeg-build-script#164]
Zlib has had a minor revision from 1.2.12 to 1.2.13 and is no longer hosting https://www.zlib.net/zlib-1.2.12.tar.gz as referenced in the build file.

**Comment by GeneralErrorOK** [comment]
Ha! I was working a sed replace into my Dockerfiles just when I saw the new commit. Thanks!

**Comment by throttlehead-dev** [comment]
Has no one put in a PR for this yet? I can get it knocked out tomorrow am.

I'll put in an email to them letting them know that a `/latest` or `/stable` url in their repo would be really helpful for projects that have come to rely on it.

**Comment by madler** [comment]
There is always an http://zlib.net/zlib.tar.gz , which is the latest release.

**Comment by scgreenhalgh** [comment]
> There is always an http://zlib.net/zlib.tar.gz , which is the latest release.

Thanks for the idea but it’s never good practice to just download the latest version without testing it first. But I am surprised that they don’t leave older versions available for download, even if for a short time. This just asks for anything automated to break like this build script did.

**Comment by madler** [comment]
I'm the they. It sounded like someone here was looking for a link to the latest version, which is what I provided.

You can find all of the versions, going back 27 years, including the current version, in https://zlib.net/fossils/ .

**Comment by scgreenhalgh** [comment]
Oops, I guess this is a case for “/r/dontyouknowwhoiam”, apologies for that. I did the pull request as it was calling and trying to download the specific older version which was replaced and therefore broke the build script. What is your policy on feature depreciation? If you think it’s ok to just always pull latest then I’ll make that change. Thanks in advance!

**Comment by scgreenhalgh** [comment]
> Has no one put in a PR for this yet? I can get it knocked out tomorrow am.
> 
> I'll put in an email to them letting them know that a `/latest` or `/stable` url in their repo would be really helpful for projects that have come to rely on it.

Already done and accepted from memory.

**Comment by markus-perl** [comment]
Hey Mark, thank you for the links and the great work you've done over the last couple of years. I'm using zlib in so many projects. I wasn't aware of the fossils archive, but I'm going to change the script so it will use the fossils link in the next version. And thanks to all for providing the pull requests and all the input. This really helps a lot to maintain the project.
