### ISSUE TITLE
Please add hardware acceleration via --enable-vaapi

### ISSUE THREAD

**Issue by 350d** [markus-perl/ffmpeg-build-script#18]
You can follow this gist to update your script with hardware acceleration support

https://gist.github.com/Brainiarc7/95c9338a737aa36d9bb2931bed379219

**Comment by DwarfFighterCleric** [comment]
Yes, I'm looking for builds that come with Vaapi and libfdk_aac

**Comment by markus-perl** [comment]
Added with commit 30d29612e467bbf3cff4db016f4dad1681174ae1.
