### ISSUE TITLE
ERROR: aom >= 1.0.0 not found using pkg-config

### ISSUE THREAD

**Issue by sergiks** [markus-perl/ffmpeg-build-script#24]
Under Amazon Web Services [Amazon Linux AMI](https://console.aws.amazon.com/ec2/v2/home#Images:visibility=public-images;search=amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2) 2018.03 on EC2 t2.micro instance I was trying to compile ffmpeg for use with AWS Lambda.

    sudo yum update -y
    sudo yum groupinstall -y "Development Tools" "Development Libraries"
    bash <(curl -s "https://raw.githubusercontent.com/markus-perl/ffmpeg-build-script/master/web-install.sh?v1")

Command went well including "building ffmpeg ... Done" but failed after that with error

    ERROR: aom >= 1.0.0 not found using pkg-config

    If you think configure made a mistake, make sure you are using the latest
    version from Git.  If the latest version fails, report the problem to the
    ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
    Include the log file "ffbuild/config.log" produced by configure as this will help
    solve the problem.

**Comment by sergiks** [comment]
I tried updating the build_ffmpeg script with the "aom" url for `refs/tags/v1.0.0-errata1`:

    https://aomedia.googlesource.com/aom/+archive/add4b15580e410c00c927ee366fa65545045a5d9.tar.gz

Deleted the folder `packages/aom-build` and re-run `build_ffmpeg --build`
but even with that "patch" module version looks old:

    PKG_CONFIG_PATH="/home/ec2-user/ffmpeg-build-script/packages/aom_build/"   pkg-config --modversion aom
    0.1.0

**Comment by sergiks** [comment]
Temporary solution for me was to edit `build-ffmpeg`: line 376 change from

	--enable-libaom

to

	--disable-libaom

Eventually built ffmpeg runs perfectly under AWS Lambda.

**Comment by markus-perl** [comment]
Hi Sergiks, 

Due to the lack of time and resources, I can currently only support the following platforms:

Mac OSX 10.14 64Bit XCode 10.1
Debian 9.4

You can also try to compile FFmpeg on a Debian machine and then copy the resulting binaries to your EC2 instance.
