### ISSUE TITLE
4.2 update broke libvpx build

### ISSUE THREAD

**Issue by gorgarp** [markus-perl/ffmpeg-build-script#29]
building libvpx
=======================
Downloading https://github.com/webmproject/libvpx/archive/v1.8.1.tar.gz
... Done
/dev/fd/63: line 197: cd: too many arguments

**Comment by gorgarp** [comment]
@markus-perl fixed :) Thanks!

**Comment by markus-perl** [comment]
I'm glad I could help :-)
