### ISSUE TITLE
sdl2 support

### ISSUE THREAD

**Issue by dannephoto** [markus-perl/ffmpeg-build-script#35]
Thanks for a really helpful script solution. I compiled a static version but when testing it out on a friends computer it cries about sdl2 dependency. I suspect he runs an old set up but is there anyway otherwise to enable sdl2 support into the binary? Here is what it looks like:
```
./ffmpeg -h
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/masc/Desktop/./ffmpeg
  Reason: image not found
Trace/BPT trap: 5
```

EDIT: His os is OSX 10.9.5 by the way.

**Comment by markus-perl** [comment]
Hi Dannephoto, I'm closing this issue as no one has an answer. 10.9.5 is a very old OSX version which is also not supported by the build script.

**Comment by dannephoto** [comment]
Yes, no problem. Your script and some workarounds took me all the way on most computers. Great script.
