### ISSUE TITLE
Add LibSRT

### ISSUE THREAD

**Issue by rtgoodwin** [markus-perl/ffmpeg-build-script#45]
Hi hi! 

Still a huge fan of this script, still feels like magic :) 

Was wondering if it was possible to add LibSRT officially, as it is getting more and more popular (especially for "quick, dependency-free" deploys as relay servers). 

I have a patch that will compile, but it's not ideal for 2 reasons: 

1. Currently have to checkout an older git hash because of an incompatibility with released FFMPEG and deprecated calls. This can be worked around with an older commit hash, an older SRT version, or just wait for new FFMPEG (or HEAD). No biggies here. (see "patch" below). I have it as `git` but could of course `wget` the commit archive. 
2. More importantly, the SRT package doesn't seem to compile fully statically in the context of this build script. Technically what fails are the included apps, which AFAICT aren't needed at all for libsrt features, but makes me nervous. I spoke at length with the devs in https://github.com/Haivision/srt/issues/1172 and the project seems to have no problem compiling statically, but I couldn't figure out what about this build script makes it such that it won't compile statically in the context of the script. Given that it is kind of the only other thing that compiles after openssl (besides FFMPEG), I wonder if there's some tweak to the openssl build needed. I tried everything I could think of. Maybe something super simple that will make sense to you all :)  Issue seen on Ubuntu (presumably Deb) and Docker; seemed to work on Darwin but haven't quite pinned that down, and the remote VM use case is the point anyway. 

Love to work with you on making this work! 

Hacky Patch: 
```
if build "srt"; then
        cd "$PACKAGES"
        git clone https://github.com/Haivision/srt.git
        cd srt
        git checkout 10ed37b6d4b49a3042213b029f0de6bca4bcfe83
        #sed -i -e 's/${name} ${srt_link_library})/${name} ${srt_link_library} ${WITH_EXTRALIBS})/' CMakeLists.txt
        cmake -DCMAKE_INSTALL_PREFIX:PATH="${WORKSPACE}" -DENABLE_SHARED=OFF -DENABLE_STATIC=ON -DENABLE_APPS=ON -DWITH_EXTRALIBS="-lz -ldl" .
       # if you just set -DENABLE_APPS=OFF these patches aren't needed since it's the included apps that will fail to compile against static ffmpeg
        sed -i -e 's/libsrt.a -ldl -lssl -lcrypto -lpthread/libsrt.a -lssl -lcrypto -lz -ldl -lpthread/' CMakeFiles/srt-live-transmit.dir/link.txt
        sed -i -e 's/libsrt.a -ldl -lssl -lcrypto -lpthread/libsrt.a -lssl -lcrypto -lz -ldl -lpthread/' CMakeFiles/srt-tunnel.dir/link.txt
        sed -i -e 's/libsrt.a -ldl -lssl -lcrypto -lpthread/libsrt.a -lssl -lcrypto -lz -ldl -lpthread/' CMakeFiles/srt-file-transmit.dir/link.txt
        execute make -j $MJOBS
        execute make install
        build_done "srt"
fi

.... 
--enable-libsrt

**Comment by rtgoodwin** [comment]
FWIW, I had already tried https://github.com/markus-perl/ffmpeg-build-script/pull/47 for this. Had high hopes though! :)

**Comment by markus-perl** [comment]
I've created an extra branch: https://github.com/markus-perl/ffmpeg-build-script/tree/libsrt

What are these apps for (ENABLE_APPS)? I disabled them but the script compiled with and without them.

Can you check if the script works for you. Also an example would be good, how srt can be tested.

**Comment by rtgoodwin** [comment]
I don't believe the apps are needed either for this use case. 

I did confirm that the SRT cmake files don't seem to properly include the pkgconfig "--static" variables that are needed when compiling against static OpenSSL. So that's a fix for them to make IMO, but I'm fine w/o the apps anyway since your/our goal is a single binary. 

As for an example, I'm not sure how you'd like to see that. The OBS wiki perhaps provides a great example of usage: https://obsproject.com/wiki/Streaming-With-SRT-Protocol

From a CI perspective, all you would need to do is start ffmpeg with an srt input line as indicated at the bottom of that page. If it doesn't exit immediately, it's probably working. To effect a real test you'd have to initiate an SRT stream (in this example) to that instance, but I don't think that's required. In my experience to date, if ffmpeg starts and listens then you're good to go. Any bugs at that point are in the lib or ffmpeg itself and not with the script. 

On the libsrt branch it shows even with master and I'm not seeing the SRT step. Am I missing something? 

And btw thanks for even considering this; it's been a real journey as I figured all this out :)

**Comment by rtgoodwin** [comment]
> I've created an extra branch: https://github.com/markus-perl/ffmpeg-build-script/tree/libsrt
> 
> What are these apps for (ENABLE_APPS)? I disabled them but the script compiled with and without them.
> 
> Can you check if the script works for you. Also an example would be good, how srt can be tested.

Actually it's interesting that it compiled with the apps for you. That was the source of the whole issue in the first place. I think it worked for me on macOS but not Ubuntu, hard to remember. At any rate my supposition about not needing them stands :)

**Comment by rtgoodwin** [comment]
PR submitted: https://github.com/markus-perl/ffmpeg-build-script/pull/52

TBH I'm now very curious how you got the apps to build, it still fails for me. What version of SRT did you use, what environment, etc?

**Comment by d-averkiev** [comment]
I just used your path @rtgoodwin and got statically linked ffmpeg binaries with libsrt support. It successfully built  them on Ubuntu 16.04 and Ubuntu 18.04. Thank you for your effort :+1:

**Comment by markus-perl** [comment]
I've merged the pull request with some tweaks.

**Comment by rtgoodwin** [comment]
Why the dual configure and cmake statements? I removed the configure because it seemed to have a requirement on tclsh. It did just fail to build in Docker for me (where tclsh is not present; not sure how common this is on other Linux?)
