### ISSUE TITLE
in centos7 build pkg-config error

### ISSUE THREAD

**Issue by alongL** [markus-perl/ffmpeg-build-script#48]
error:
 GNU libiconv not in use but included iconv.h is from libiconv 

solution:  Add   --with-libiconv=gnu  in ./configure  command .
like this:

```
execute ./configure --silent --prefix="${WORKSPACE}" --with-pc-path="${WORKSPACE}"/lib/pkgconfig --with-internal-glib   --with-libiconv=gnu
```

**Comment by markus-perl** [comment]
Please see README.md: 

> Use this script at your own risk. I maintain this script in my spare time. Please do not file bug reports for systems other than Debian 10 and macOS 10.15.x because I don't have the resources and the time to maintain other systems.

Supporting centos would require a larger rewrite and I don't have the time for this. Please file a pull request if you want to support centos.
