### ISSUE TITLE
in centos 7 openssl and libaom  is installed  in $workspace/lib64.  

### ISSUE THREAD

**Issue by alongL** [markus-perl/ffmpeg-build-script#49]
In centos 7 openssl is installed  in $workspace/lib64.    
libaom is also in $workspace/lib64

When building ffmpeg it will fail for not found openssl.
libaom is the same.

If i copy them to  $workspace/lib  and modify  $workspace/lib/pkgconfig/libssl.pc  libcrypto.pc  openssl.pc   libaom.pc
then compile ffmpeg sucess.

Is that the same in your machine?

Would  some fix operation be  performed?

**Comment by markus-perl** [comment]
Please see README.md: 

> Use this script at your own risk. I maintain this script in my spare time. Please do not file bug reports for systems other than Debian 10 and macOS 10.15.x because I don't have the resources and the time to maintain other systems.

Supporting centos would require a larger rewrite and I don't have the time for this. Please file a pull request if you want to support centos.
