### ISSUE TITLE
Fails in building opencore

### ISSUE THREAD

**Issue by cjattard** [markus-perl/ffmpeg-build-script#51]
The script is exiting on trying to build opencore

terminal log--- 

building opencore
=======================
Downloading https://deac-riga.dl.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.5.tar.gz
... Done
Failed to extract opencore-amr-0.1.5.tar.gz

**Comment by markus-perl** [comment]
Can't confirm. Please run `./build-ffmpeg --cleanup` and try again.
