### ISSUE TITLE
Issue during building SRT

### ISSUE THREAD

**Issue by julien-bis** [markus-perl/ffmpeg-build-script#54]
The script exit on building SRT
I did a common install on Ubuntu Focal Fossa.

> building srt
=======================
Downloading https://github.com/Haivision/srt/archive/v1.4.1.tar.gz
... Done
$ ./configure --prefix=/root/ffmpeg-build-script/workspace --disable-shared --enable-static
./build-ffmpeg: ./configure: /usr/bin/tclsh: bad interpreter: No such file or directory

> Failed to Execute ./configure --prefix=/root/ffmpeg-build-script/workspace --disable-shared --enable-static

I've tried to cleanup then try again but the same issue occured.
What's wrong ? Thanks

**Comment by rtgoodwin** [comment]
Remove the configure line above the cmake line; I think it was included incorrectly, have pinged @markus-perl

**Comment by markus-perl** [comment]
Fixed in v1.16
