### ISSUE TITLE
Add `--enable-lv2` support?

### ISSUE THREAD

**Issue by tlan16** [markus-perl/ffmpeg-build-script#55]
Hi,

I want to do noise suppression with ffmpeg rnnoise model, like described in [this](https://stackoverflow.com/questions/58600620/ffmpeg-complex-filtering-how-to-get-around) post. Can you show me how to do that, or maybe included this in your script?

If I simply included `--enable-lv2` in ffmpeg configure, it shows this error:
> ERROR: lilv-0 not found using pkg-config

**Comment by tlan16** [comment]
I couldn't get it working modifying the shell script in this repo. 

So I installed ` sudo apt install liblilv-dev` and followed the official ffmpeg ubuntu compilation guild with the `--enable-lv2` flag, it worked.

**Comment by jbb26354** [comment]
...What do I need to modify in the script, to ensure that ffmpeg will output 10-bit color files on a MacBook Pro? Or, is encoding 10-bit video on a MacBook Pro impossible?

**Comment by markus-perl** [comment]
Added with commit 3563a1cc5365409b51f497f71be6a0391c908c02.
