### ISSUE TITLE
Create full static binary need option 

### ISSUE THREAD

**Issue by centosup** [markus-perl/ffmpeg-build-script#60]
Please add option for create full static binary without system libraries dependencies.

I want to compile code on Debian and run on CentOS, but this is impossible because LibC,  Libptheads and some other libs are dynamic

Look at projects https://github.com/zimbatm/ffmpeg-static - this is full static buld and I can comple this in Ubuntu and run on the CentOS.

Thank you 😊

**Comment by centosup** [comment]
just add option --extra-ldexeflags="-static"


[patch.txt](https://github.com/markus-perl/ffmpeg-build-script/files/5419734/patch.txt)

**Comment by AkashiSN** [comment]
https://github.com/markus-perl/ffmpeg-build-script/pull/61

**Comment by markus-perl** [comment]
Merged. I released V1.18 with these changes.: https://github.com/markus-perl/ffmpeg-build-script/releases/tag/v1.18
