### ISSUE TITLE
Add SVT-AV1 support

### ISSUE THREAD

**Issue by veikk0** [markus-perl/ffmpeg-build-script#70]
The [SVT-AV1](https://github.com/AOMediaCodec/SVT-AV1) encoder is in some ways better than the reference AV1 encoder (libaom). It has much better multithreading, so it's not a PITA to use all your CPU cores for AV1 encoding.

I've been building from git according to the [Debian/Ubuntu compilation guide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libsvtav1) for a few months and the build process hasn't broken so far.

**Comment by markus-perl** [comment]
Added with commit d9d9701da4592033c43fb70146de5217e42364e3.
