### ISSUE TITLE
Hope to increase support for rkmpp

### ISSUE THREAD

**Issue by online2311** [markus-perl/ffmpeg-build-script#75]
I hope to increase the support for rkmpp. I have tried to compile static files by myself, but it fails every time. As far as I know, it may require the support of the library and send my warm wishes.

https://github.com/rockchip-linux/mpp

https://github.com/rockchip-linux/linux-rga

https://github.com/rockchip-linux/libdrm-rockchip

**Comment by online2311** [comment]
Although rkmpp can only decode the hardware of Rockchip chips, it is needed.

**Comment by markus-perl** [comment]
I don't have a rockchip device; therefore, I can't support this chip. Please provide a pull request if you want to support this library. Also, libdrm-rockchip is marked as deprecated. We do not support deprecated libraries.
