### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by Aleksid1** [markus-perl/ffmpeg-build-script#77]
I suggest to include MACOSX_DEPLOYMENT_TARGET for macOS x86_64 target.
For example, MACOSX_DEPLOYMENT_TARGET=10.11

**Comment by markus-perl** [comment]
Hi Aleksid1, can you explain why you would recommend this setting? What would happen if the script is executed with this target on a 10.10 machine?

- Markus

**Comment by Aleksid1** [comment]
Hi Markus,

I modified your script to build dynamic libraries. And I discovered that by default  minimum macOS version is set as 11.0 (as my current macOS version). I checked with: otool -l libraryname.dylib

So these dylibs cannot be used on macOS 10.12 High Sierra - I get error on startup of my app.

When I added export MACOSX_DEPLOYMENT_TARGET=10.11 to the script the produced dylibs are not works fine on macOS High Sierra.

Probaby MACOSX_DEPLOYMENT_TARGET=10.10 would be fine for x86_64 Mac (and 11.0 for Apple M1 as already set in the script).

**Comment by markus-perl** [comment]
The script builds a binary with the license "nonfree and unredistributable". You should not include such binary or library in any app.

**Comment by Aleksid1** [comment]
"I modified your script"

**Comment by markus-perl** [comment]
But as I can see, changing the deployment target makes only sense if you want to distribute the built binary/library on older systems? Otherwise, we can rely on the systems deployment target.
