### ISSUE TITLE
Deepin Linux build to failed

### ISSUE THREAD

**Issue by 8MiYile** [markus-perl/ffmpeg-build-script#89]
`
ffmpeg-build-script v1.25
=========================

Using 4 make jobs simultaneously.

building pkg-config
=======================
pkg-config-0.29.2.tar.gz has already downloaded.
Extracted pkg-config-0.29.2.tar.gz
$ ./configure --silent --prefix=/home/bmi_yile/ffmpeg-build-script/workspace --with-pc-path=/home/bmi_yile/ffmpeg-build-script/workspace/lib/pkgconfig --with-internal-glib
$ make -j 4
$ make install

building lv2
=======================
Downloading https://lv2plug.in/spec/lv2-1.18.2.tar.bz2 as lv2-1.18.2.tar.bz2
... Done
Extracted lv2-1.18.2.tar.bz2
$ ./waf configure --prefix=/home/bmi_yile/ffmpeg-build-script/workspace --lv2-user
$ ./waf
$ ./waf install

building waflib
=======================
Downloading https://gitlab.com/drobilla/autowaf/-/archive/b600c928b221a001faeab7bd92786d0b25714bc8/autowaf-b600c928b221a001faeab7bd92786d0b25714bc8.tar.gz as autowaf.tar.gz
... Done
Extracted autowaf.tar.gz

building serd
=======================
Downloading https://gitlab.com/drobilla/serd/-/archive/v0.30.10/serd-v0.30.10.tar.gz as serd-v0.30.10.tar.gz
... Done
Extracted serd-v0.30.10.tar.gz
$ cp -r /home/bmi_yile/ffmpeg-build-script/packages/autowaf/ansiterm.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Build.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/ConfigSet.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Configure.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Context.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/COPYING /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Errors.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/extras /home/bmi_yile/ffmpeg-build-script/packages/autowaf/fixpy2.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/__init__.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Logs.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Node.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Options.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/processor.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/README.md /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Runner.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Scripting.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/TaskGen.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Task.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Tools /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Utils.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/waf /home/bmi_yile/ffmpeg-build-script/packages/serd-v0.30.10/waflib/
$ ./waf configure --prefix=/home/bmi_yile/ffmpeg-build-script/workspace --static --no-shared --no-posix
$ ./waf
$ ./waf install

building pcre
=======================
Downloading https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz as pcre-8.44.tar.gz
... Done
Extracted pcre-8.44.tar.gz
$ ./configure --prefix=/home/bmi_yile/ffmpeg-build-script/workspace --disable-shared --enable-static
$ make -j 4
$ make install

building sord
=======================
Downloading https://gitlab.com/drobilla/sord/-/archive/v0.16.8/sord-v0.16.8.tar.gz as sord-v0.16.8.tar.gz
... Done
Extracted sord-v0.16.8.tar.gz
$ cp -r /home/bmi_yile/ffmpeg-build-script/packages/autowaf/ansiterm.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Build.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/ConfigSet.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Configure.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Context.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/COPYING /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Errors.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/extras /home/bmi_yile/ffmpeg-build-script/packages/autowaf/fixpy2.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/__init__.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Logs.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Node.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Options.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/processor.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/README.md /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Runner.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Scripting.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/TaskGen.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Task.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Tools /home/bmi_yile/ffmpeg-build-script/packages/autowaf/Utils.py /home/bmi_yile/ffmpeg-build-script/packages/autowaf/waf /home/bmi_yile/ffmpeg-build-script/packages/sord-v0.16.8/waflib/
$ ./waf configure --prefix=/home/bmi_yile/ffmpeg-build-script/workspace CFLAGS=-I/home/bmi_yile/ffmpeg-build-script/workspace/include --static --no-shared --no-utils
Setting top to                                : /home/bmi_yile/ffmpeg-build-script/packages/sord-v0.16.8 
Setting out to                                : /home/bmi_yile/ffmpeg-build-script/packages/sord-v0.16.8/build 
Checking for 'gcc' (C compiler)               : /usr/bin/gcc 
Checking for flag '-std=c99'                  : yes 
Checking for flag '-std=c++11'                : yes 
Checking for program 'pkg-config'             : /home/bmi_yile/ffmpeg-build-script/workspace/bin/pkg-config 
Checking for 'serd-0 >= 0.30.0'               : not found 
The configuration failed
(complete log in /home/bmi_yile/ffmpeg-build-script/packages/sord-v0.16.8/build/config.log)

Failed to Execute ./waf configure --prefix=/home/bmi_yile/ffmpeg-build-script/workspace CFLAGS=-I/home/bmi_yile/ffmpeg-build-script/workspace/include --static --no-shared --no-utils
`

**Comment by markus-perl** [comment]
Deepin Linux is not supported. See Readme file.
