### ISSUE TITLE
Failed to extract ffmpeg

### ISSUE THREAD

**Issue by christau** [markus-perl/ffmpeg-build-script#9]
When I ran this script it always broke at that part

> building ffmpeg
=======================
Downloading http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 
... Done
Failed to extract ffmpeg-snapshot.tar.bz2 

After a little investigation it turned out that in line [#309](https://github.com/markus-perl/ffmpeg-build-script/blob/master/build-ffmpeg#L309) there are 2 trailing spaces inside the quotes. After removing them it worked.

So this line

> download "http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 " "ffmpeg-snapshot.tar.bz2 "

should be

> download "http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2" "ffmpeg-snapshot.tar.bz2" 

Thanks for sharing your script!

**Comment by markus-perl** [comment]
Fixed.
